docs: Added walktrough for Programming Gateway using MPLAB IPE
TheThingsNetwork/docs pull request #223
Opened 2018-03-22 13:51 UTC by KrishnaIyer

2018-03-22 13:56 UTC, htdvisser requested changes

2018-03-22 13:56 UTC, htdvisser commented on _content/gateways/gateway/programhexfile.md
> +   **Loac Hex File**
typo

2018-03-22 13:56 UTC, htdvisser commented on _content/gateways/gateway/programhexfile.md
> +Now load the hex file from your PC. The IPE checks it for validity.
This does not say anything about the IPE warning about addresses that don't exist on the PIC

2018-03-22 14:27 UTC, KrishnaIyer commented on _content/gateways/gateway/programhexfile.md
> +   **Loac Hex File**
done

2018-03-22 14:34 UTC, KrishnaIyer commented on _content/gateways/gateway/programhexfile.md
> +Now load the hex file from your PC. The IPE checks it for validity.
@htdvisser: You know why it's happening here?
Usually this issue would be something to do with the `.map` file or the linker scripts

2018-03-22 15:26 UTC, htdvisser commented on _content/gateways/gateway/programhexfile.md
> +Now load the hex file from your PC. The IPE checks it for validity.
I have no idea. I just took the screenshots (as a noob in progging) and noticed the warning

2018-03-22 16:00 UTC, KrishnaIyer commented on _content/gateways/gateway/programhexfile.md
> +Now load the hex file from your PC. The IPE checks it for validity.
Well I programmed another gateway and I didn't see this error. It should be an MPLAB specific thing. I think we can add a comment on this and close this PR

2018-03-22 16:02 UTC, htdvisser commented on _content/gateways/gateway/programhexfile.md
> +   **Loac Hex File**
Github still shows the typo. Forgot to push maybe?

2018-03-22 16:31 UTC, KrishnaIyer commented on _content/gateways/gateway/programhexfile.md
> +   **Loac Hex File**
oopsey

2018-03-23 08:34 UTC, htdvisser approved these changes

2018-03-23 08:36 UTC, merged