Add Pycom's Pygate to the list of Gateways
TheThingsNetwork/docs pull request #294
Opened 2019-03-06 23:34 UTC by danicampora

Just description and specs for now. Setup instructions and guidelines will come later before the Gateway starts shipping.

2019-03-06 23:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TheThingsNetwork/docs?pullRequest=294) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/TheThingsNetwork/docs?pullRequest=294) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TheThingsNetwork/docs?pullRequest=294) it.</sub>

2019-03-07 07:09 UTC, johanstokking requested changes
Thanks! Please also add installation instructions for TTN/TTI.

2019-03-07 07:09 UTC, johanstokking commented on _content/gateways/pycom/index.md
> +# Pygate description
Please follow the header format so this page gets rendered correctly.

For example:

```
---
title: Pycom Pygate
section: Hardware
redirect_from:
 - /pycom/
image: /gateways/pycom/image.jpg
zindex: 900
---
```

You may also need to change this header.

2019-03-07 07:55 UTC, danicampora commented
@johanstokking thanks for the feedback. I will follow the header format as you suggest. Regarding the installation instructions, that will come later as we haven't prepared that yet (the Gateway is still not in production). Can we add the installation instructions later on?

2019-03-07 09:49 UTC, johanstokking commented
@danicampora since this is documentation, we need instructions here. For showing a product page only, we have the [Marketplace](https://www.thethingsnetwork.org/marketplace). cc @rish-c

2019-03-27 19:30 UTC, johanstokking commented
@danicampora what is the status of the gateway production? Any manuals yet?

2020-10-21 13:18 UTC, benolayinka commented
Closing due to inactivity

2020-10-21 13:18 UTC, closed without merging