doc: Add antenna types
TheThingsNetwork/docs pull request #522
Opened 2022-08-12 08:58 UTC by pradeeka7

#### Summary

This study material includes some of the popular antenna types used with LoRaWAN end devices and gateways.

#### Screenshots

![image](https://user-images.githubusercontent.com/36432168/184319897-920f4482-b45f-4fbc-823e-ecda0100783c.png)

#### Changes

- ...
- ...

#### Notes for Reviewers

@benolayinka Can you review?

#### Checklist

- [X] Scope: The referenced issue is addressed, there are no unrelated changes.
- [X] Run Locally: Verified that the docs build using `make server`, posted screenshots, verified external links.
- [X] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [X] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

2022-11-15 18:10 UTC, nejraselimovic requested changes

2022-11-15 18:10 UTC, nejraselimovic commented on doc/content/lorawan/antenna-types/_index.md
> +image credits: [SparkFun Electronics](https://learn.sparkfun.com/)
If you use _image courtesy of ..._ in one page, please be consistent and use the same in others as well

2022-11-15 18:10 UTC, nejraselimovic commented on doc/content/lorawan/antenna-types/_index.md
> +Spring antennas (also known as Coil/Helical antennas) are made from coiled wires (usually copper or aluminium) that reduce the antenna’s length. These antennas are suitable for use with LoRa modules
```suggestion
Spring antennas (also known as coil/helical antennas) are made from coiled wires (usually copper or aluminium) that reduce the antenna’s length. These antennas are suitable for use with LoRa modules with low transmission power (up to 100mW) and are also perfect for end devices with space constraints.
```

2022-11-15 18:10 UTC, nejraselimovic commented on doc/content/lorawan/antenna-types/_index.md
> +
collinear antenna, not Colinear antenna

2022-11-16 23:44 UTC, pradeeka7 commented
@nejraselimovic done

2022-11-26 09:53 UTC, merged