doc: Add radio propagation
TheThingsNetwork/docs pull request #525
Opened 2022-09-12 12:39 UTC by pradeeka7

#### Summary

Add Radio Propagation tutorial for The Things Advanced + Network Management

#### Screenshots

![image](https://user-images.githubusercontent.com/36432168/189651974-9dfef3db-24a8-4fed-bf7b-4aacba461c1d.png)

#### Changes

- new document
- ...

#### Notes for Reviewers

@benolayinka Could you please provide new images for each type of propagation based on the following document?
https://docs.google.com/document/d/154WxryZxFyeRNCf03HaqPHC34rLmC_jlHx3UAXNUZeA/edit?usp=sharing

This document is mainly based on:
[TTN Webcast | Radio Theory Crash Course - YouTube](https://www.youtube.com/watch?v=1ZUvyg5zaDg)

#### Checklist

- [X] Scope: The referenced issue is addressed, there are no unrelated changes.
- [X] Run Locally: Verified that the docs build using `make server`, posted screenshots, verified external links.
- [X] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [X] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

2022-09-12 13:12 UTC, jpmeijers commented
`Reflections are often allowed to get signals even in dense urban environments.` - the wording in this sentence is a little strange. Maybe rephrase?

2022-09-12 13:21 UTC, pradeeka7 commented
> `Reflections are often allowed to get signals even in dense urban environments.` - the wording in this sentence is a little strange. Maybe rephrase?

Thanks. will rephrase.

2022-11-15 18:30 UTC, nejraselimovic requested changes

2022-11-15 18:30 UTC, nejraselimovic commented on doc/content/lorawan/radio-propagation/_index.md
> +Line of Sight (LoS) is a type of propagation that can transmit and receive data only where the transmitter and receiver are in view of each other without any obstacles between them. Even in the LoS,
The first sentence is not really correct. LoS propagation is a type of propagation where signal waves travel along direct transmitter-receiver path without any obstacles. This definition doesn't have anything to do with transceiver's ability to transmit and receive data. Some transceivers can transmit/receive only if LoS exists, while others can do it if LoS doesn't exist, i.e. if there's obstacles between them. 

This part "a type of propagation that can transmit and receive data ..." is also not correct - the propagation cannot transmit or receive anything.

2022-11-15 18:30 UTC, nejraselimovic commented on doc/content/lorawan/radio-propagation/_index.md
> +Attenuation is the loss of signal strength during transmission because of the absorption by various obstacles/materials.
Not necessarily absorption, there is a bunch of reasons, for example reflection. Please write that absorption is just one of possible causes.

2022-11-15 18:30 UTC, nejraselimovic commented on doc/content/lorawan/radio-propagation/_index.md
> +This type of propagation happens a lot in urban environments. A building or a mountain may block the transmitter and receiver antennas creating a shadow zone. These buildings and mountains act as kni
```suggestion
This type of propagation happens a lot in urban environments. A building or a mountain may block the transmitter and receiver antennas, creating a shadow zone. These buildings and mountains act as knife edges. When the signal passes over the knife-edge at the top of the building or mountain, it is diffracted into the shadow zone. This will usually provide spotty coverage, however, this is important to urban propagation to offer more coverage.
```

2022-11-15 18:30 UTC, nejraselimovic commented on doc/content/lorawan/radio-propagation/_index.md
> +Air in the troposphere contains enough particles up to 10 km. They reliably scatter (throw in various random directions) a small number of radio signals back down to earth. For example, with the scat
Enough particles for what?

2022-11-15 18:30 UTC, nejraselimovic commented on doc/content/lorawan/radio-propagation/_index.md
> +Cities are a good example of such an environment. Obstacles like buildings reflect signals and create multiple paths for the signals to follow. Buildings made out of good conductors reflect nearly al
Cities are a good example of which environment?

Obstacles reflect signals and create multiple paths for the signals to follow? What does this mean? I think you want to describe multipath fading here, but this just doesn't make any sense. What exactly are those paths that signals are following?

Reflections are often allowed to get signals..? What does this even mean?

2022-12-07 01:59 UTC, pradeeka7 commented
I withdraw this pull request.

2022-12-07 01:59 UTC, closed without merging