doc: Split into subpages with minor edits
TheThingsNetwork/docs pull request #541
Opened 2023-08-18 01:10 UTC by pradeeka7

#### Summary

This PR is related to the issue Large volume of text in Regional Parameters page #540
https://github.com/TheThingsNetwork/docs/issues/540

#### Screenshots

![image](https://github.com/TheThingsNetwork/docs/assets/36432168/113f53bf-4060-495b-a0dd-b838ad944723)

#### Changes

- Split into subpages
- Updated with the latest specifications 1.0.4
- Updated subbands

#### Notes for Reviewers

@nejraselimovic Can you please review this?

#### Checklist

- [X] Scope: The referenced issue is addressed, there are no unrelated changes.
- [X] Run Locally: Verified that the docs build using `make server`, posted screenshots, verified external links.
- [X] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [X] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

2023-11-08 00:54 UTC, pradeeka7 commented
@nejraselimovic / @benolayinka Can you please proceed with this?

2023-11-08 18:58 UTC, nejraselimovic requested changes
First of all, sorry for the delay, it's hard to track where my review is needed when I'm not assigned as a reviewer, but just tagged. I will check how to fix that so we don't experience this again. 

The PR looks fine to me, just please change tables according to my suggestion, to have them just like in TTI docs.

2023-11-08 18:58 UTC, nejraselimovic commented on doc/content/lorawan/regional-parameters/_index.md
> +  <td><strong>Plan ID</strong>
Please change this whole table with something like this:

```
|   Plan ID  |   Frequency Plan |  Common Name   |
| ---------- | ---------------- | -------------- |
| 1 | EU863-870 | EU868 |
| 2 | US902-928 | US915 |
| 3 | CN779-787 | CN779 |
```

2023-11-08 18:58 UTC, nejraselimovic commented on doc/content/lorawan/regional-parameters/_index.md
> +  <td><strong>Plan ID</strong>
It will render the same, but the code is much more readable

2023-11-14 19:07 UTC, nejraselimovic requested changes

2023-11-14 19:07 UTC, nejraselimovic commented on doc/content/lorawan/regional-parameters/eu868/_index.md
> +| Duty cycle (take the maximum) | Equation: Time-On-Air = number of seconds per day X duty cycle | Maximum allowed Time-On-Air per day, per device |
Please remove equation from table heading, put it under or below the table, leave only "Time-On-Air" here

2023-11-14 19:07 UTC, nejraselimovic commented on doc/content/lorawan/regional-parameters/eu868/_index.md
> +| Duty cycle (take the maximum) | Equation: Time-On-Air = number of seconds per day X duty cycle | Maximum allowed Time-On-Air per day, per device |
Also, replace all notes like "take the maximum" from the table heading, or at least use "Max duty cycle" or something like that. It should be as short as possible. Pls apply this for all tables in this PR and request another review

2023-11-24 07:19 UTC, nejraselimovic approved these changes

2023-11-26 17:08 UTC, merged