Add Stack info links
TheThingsNetwork/docs pull request #551
Opened 2024-04-22 14:34 UTC by LDannijs

#### Summary

Add some info sections with links to the Stack docs. Closes #550 

#### Changes

- add info boxes to some of the sections

#### Notes for Reviewers

...

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Run Locally: Verified that the docs build using `make server`, posted screenshots, verified external links.
- [x] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

2024-06-22 16:45 UTC, nejraselimovic requested changes
hey @LDannijs, sorry for not seeing this before, reviewers weren't assigned. Just fix TTS tags and we can merge this

2024-06-22 16:45 UTC, nejraselimovic commented on doc/content/lorawan/adaptive-data-rate/_index.md
> +Check [The Things Stack documentation](https://www.thethingsindustries.com/docs/reference/adr/#how-adr-works) for more specifics on how ADR works on the Stack.
```suggestion
Check [{{% tts %}} documentation](https://www.thethingsindustries.com/docs/reference/adr/#how-adr-works) for more specifics on how ADR works on the {{% tts %}}.
```

2024-06-22 16:45 UTC, nejraselimovic commented on doc/content/lorawan/end-device-activation/index.md
> +For more information on the differences between OTAA and ABP, check the [The Things Stack documentation](https://www.thethingsindustries.com/docs/the-things-stack/concepts/data-formats/).
```suggestion
For more information on the differences between OTAA and ABP, check the [{{% tts %}} documentation](https://www.thethingsindustries.com/docs/the-things-stack/concepts/data-formats/).
```

2024-06-22 16:45 UTC, nejraselimovic commented on doc/content/lorawan/message-types/index.md
> +For information on The Things Stack's specific data formats, check [The Things Stack documentation](https://www.thethingsindustries.com/docs/the-things-stack/concepts/data-formats/).
```suggestion
For information on {{% tts %}} specific data formats, check [{{% tts %}} documentation](https://www.thethingsindustries.com/docs/the-things-stack/concepts/data-formats/).
```

2024-06-22 16:45 UTC, nejraselimovic commented on doc/content/lorawan/regional-parameters/_index.md
> +For information on the specific versions of the Regional Parameters check [The Things Stack documentation](https://www.thethingsindustries.com/docs/the-things-stack/concepts/spec-regional-parameters/
```suggestion
For information on the specific versions of the Regional Parameters check [{{% tts %}} documentation](https://www.thethingsindustries.com/docs/the-things-stack/concepts/spec-regional-parameters/).
```

2024-06-24 07:27 UTC, LDannijs commented
Ehmm it seems there is no tts shortcode for The Things Network docs 😅

2024-06-24 07:35 UTC, LDannijs commented
Manually added it by referencing the Stack docs one

2024-06-25 17:48 UTC, nejraselimovic approved these changes
Awesome, thanks!

2024-06-25 17:49 UTC, merged